spring:
  application:
    name: Journal App
  main:
    allow-circular-references: true

  # MongoDB specifications
  data:
    mongodb:
      uri: mongodb+srv://parthsingh2712:iqECfthzuQzUHwkr@cluster0.2aekd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&ssl=true
      database: journaldb
      auto-index-creation: true
      #username: myjournaluser
      #password: mypassword

server:
  port: 8090

logging:
  level:
    com:
      parth:
        journalApp: DEBUG


weather:
  api:
    key: 80dceea5159c1887c3d898568216cfec


